CREATE DATABASE IF NOT EXISTS myoutuber2020;

USE myoutuber2020


SHOW TABLES;

DROP TABLE myoutuber2020.USER_TABLE;

CREATE TABLE USER_TABLE (
	USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_REGISTER_DATE DATETIME,
	NAME_PREFIX VARCHAR(10),
	FULL_NAME VARCHAR(100), 
	EMAIL_ID VARCHAR(200) NOT NULL, 
	MOBILE_NUM VARCHAR(30) NOT NULL, 
	WEBSITE VARCHAR(500),
	CHANNEL_NAME VARCHAR(500),
	YOUTUBE_URL VARCHAR(500) NOT NULL,
	ADDRESS TEXT, 
	CITY VARCHAR(500),
	COUNTRY VARCHAR(500),
	PINCODE VARCHAR(20), 
	DOB DATE,
	NICHE VARCHAR(100),
	USER_IDENTIFICATION_CODE VARCHAR(25)
);

ALTER TABLE USER_TABLE ADD UNIQUE (EMAIL_ID,MOBILE_NUM,YOUTUBE_URL);


DROP TABLE myoutuber2020.SUBSCRIBED_PLAN_USER;

CREATE TABLE myoutuber2020.SUBSCRIBED_PLAN_USER (
	USER_ID INT NOT NULL,
	PLAN_ACTIVATION_DATETIME DATETIME NOT NULL,
	PLAN_END_DATETIME DATETIME NOT NULL,
	PLAN_ID INT NOT NULL,
	PAYMENT_AMT DOUBLE NOT NULL,
	PAYMENT_CCY VARCHAR(100) NOT NULL,
	PAYMENT_STATUS VARCHAR(100) NOT NULL,
	PAYMENT_REF VARCHAR(500) NOT NULL,
	PLAN_KEY VARCHAR(100) NOT NULL
);

DROP TABLE myoutuber2020.PLAN_DETAILS;

CREATE TABLE PLAN_DETAILS (
	PLAN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	VALIDITY_TEXT VARCHAR(100) NOT NULL,
	VALIDITY_DAYS INT NOT NULL,
	PLAN_NAME VARCHAR(100) NOT NULL,
	PLAN_AMOUNT INT NOT NULL,
	PLAN_DISCOUNT INT NOT NULL,
	PLAN_CURRENCY VARCHAR(100) NOT NULL,
	PLAN_DESC VARCHAR(1000),
	PLAN_STATUS VARCHAR(50) NOT NULL,
	COUNTRY_ID VARCHAR(200) NOT NULL
);